;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Mods/GameFeatures/PeriodicMadness/Content/Localization/PeriodicMadness
DestinationPath=Mods/GameFeatures/PeriodicMadness/Content/Localization/PeriodicMadness
ManifestName=PeriodicMadness.manifest
ArchiveName=PeriodicMadness.archive
ResourceName=PeriodicMadness.locres
bSkipSourceCheck=false
bValidateFormatPatterns=true
bValidateSafeWhitespace=false
bValidateRichTextTags=false
NativeCulture=en
CulturesToGenerate=en
CulturesToGenerate=es-ES
CulturesToGenerate=fr
CulturesToGenerate=pl
CulturesToGenerate=ru
CulturesToGenerate=tr
CulturesToGenerate=uk
CulturesToGenerate=zh-Hans
CulturesToGenerate=zh-Hant
CulturesToGenerate=de
CulturesToGenerate=ja
CulturesToGenerate=pt-BR

[GatherTextStep0]
CommandletClass=GenerateTextLocalizationResource

