---
$schema: https://raw.githubusercontent.com/Satisfactory-KMods/KDataForge-Linter/refs/heads/main/src/kdataforge_linter/schemas/cdo.schema.yml
type: cdo
patches:
  - target: /Script/PeriodicMadness.PMCleanerSettings
    properties:
      - path: mStaticMeshesCleanlist
        value:
          # Caterium
          - /Game/FactoryGame/Resource/RawResources/Nodes/ResourceNode_OreGold_01
          # Copper
          - /Game/FactoryGame/Resource/RawResources/Nodes/ResourceNode_OreCopper_01
          # Quartz
          - /Game/FactoryGame/Resource/RawResources/Nodes/ResourceNode_quartz
          # Sulfur
          - /Game/FactoryGame/Resource/RawResources/Nodes/SulfurResource_01
      - path: mStaticMeshesByMaterialCleanlist
        value:
          # Bauxite
          - StaticMesh: /Game/FactoryGame/Resource/RawResources/Nodes/ResourceNode_OreIron_01
            Material: Bauxite
          # Iron
          - StaticMesh: /Game/FactoryGame/Resource/RawResources/Nodes/ResourceNode_OreIron_01
            Material: Iron
      - path: mResourceClassAllowlist
        value:
          # Mods
          - /PeriodicMadness/
          # Generic matches
          - Geyser
          # must be allowed to be replaced
          - Desc_Coal
          - Desc_Stone
          - Desc_SAM
          - Desc_NitrogenGas
          - Desc_OreUranium
          - Desc_Water
          - Desc_LiquidOil
      - path: mResourceClassReplacements
        value:
          - Target: /Game/FactoryGame/Resource/RawResources/Coal/Desc_Coal.Desc_Coal_C
            Replacement: /PeriodicMadness/Resources/Products/RawResources/Coal/Desc_PM_Coal.Desc_PM_Coal_C
          - Target: /Game/FactoryGame/Resource/RawResources/Stone/Desc_Stone.Desc_Stone_C
            Replacement: /PeriodicMadness/Resources/Products/RawResources/Stone/Desc_PM_Stone.Desc_PM_Stone_C
          - Target: /Game/FactoryGame/Resource/RawResources/SAM/Desc_SAM.Desc_SAM_C
            Replacement: /PeriodicMadness/Resources/Products/AlienTech/SAM/Desc_PM_SAM.Desc_PM_SAM_C
          - Target: /Game/FactoryGame/Resource/RawResources/NitrogenGas/Desc_NitrogenGas.Desc_NitrogenGas_C
            Replacement: /PeriodicMadness/Resources/NB/NobleGases/MixedNobleGas/Desc_PM_MixedNobleGas.Desc_PM_MixedNobleGas_C
          - Target: /Game/FactoryGame/Resource/RawResources/OreUranium/Desc_OreUranium.Desc_OreUranium_C
            Replacement: /PeriodicMadness/Resources/AC/Uranium/UraniumOre/Desc_PM_UraniumOre.Desc_PM_UraniumOre_C
          - Target: /Game/FactoryGame/Resource/RawResources/Water/Desc_Water.Desc_Water_C
            Replacement: /PeriodicMadness/Resources/Fluids/Water/Water/Desc_PM_Water.Desc_PM_Water_C
          - Target: /Game/FactoryGame/Resource/RawResources/CrudeOil/Desc_LiquidOil.Desc_LiquidOil_C
            Replacement: /PeriodicMadness/Resources/Fluids/Oil/CrudeOil/Desc_PM_CrudeOil.Desc_PM_CrudeOil_C
      - path: mFoliageItemClassAllowlist
        value:
          # Mods
          - /PeriodicMadness/
          # must be allowed to be replaced
          - Desc_Leaves
          - Desc_Mycelia
          - Desc_Stone
          - Desc_Wood
      - path: mFoliageItemClassReplacements
        value:
          - Target: /Game/FactoryGame/Resource/Parts/GenericBiomass/Desc_Leaves.Desc_Leaves_C
            Replacement: /PeriodicMadness/Resources/Products/RawResources/Leaves/Desc_PM_Leaves.Desc_PM_Leaves_C
          - Target: /Game/FactoryGame/Resource/Parts/GenericBiomass/Desc_Mycelia.Desc_Mycelia_C
            Replacement: /PeriodicMadness/Resources/Products/RawResources/Mycelia/Desc_PM_Mycelia.Desc_PM_Mycelia_C
          - Target: /Game/FactoryGame/Resource/Parts/GenericBiomass/Desc_Wood.Desc_Wood_C
            Replacement: /PeriodicMadness/Resources/Products/RawResources/Wood/Desc_PM_Wood.Desc_PM_Wood_C
          - Target: /Game/FactoryGame/Resource/RawResources/Stone/Desc_Stone.Desc_Stone_C
            Replacement: /PeriodicMadness/Resources/Products/RawResources/Stone/Desc_PM_Stone.Desc_PM_Stone_C
      - path: mWaterVolumeResourceClassReplacement
        value:
          Target: /Game/FactoryGame/Resource/RawResources/Water/Desc_Water.Desc_Water_C
          Replacement: /PeriodicMadness/Resources/Fluids/Water/Water/Desc_PM_Water.Desc_PM_Water_C
      - path: mResearchTreeClassAllowlist
        value:
          # Mods
          - /PeriodicMadness/
          # Generic matches
          - HardDrive
      - path: mSchematicClassAllowlist
        value:
          # Mods
          - /AllMapRadar/
          - /MagicMachine/
          - /PeriodicMadness/
          # Generic matches
          - Boombox
          - CoffeeCup
          - CustomizerUnlock
          - InventorySlots
          - Patterns
          - Pioneercosmetics
          - Statue
          - Tapes
      - path: mSchematicCleanupList
        value:
          - Schematic: /PeriodicMadness/Schematics/Tutorial/Schematic_PM_Tutorial1_5.Schematic_PM_Tutorial1_5_C
            ScannableResourceClassCleanlist:
              - /Game/FactoryGame/Resource/RawResources/OreCopper/Desc_OreCopper.Desc_OreCopper_C
          - Schematic: /PeriodicMadness/Schematics/Tutorial/Schematic_PM_Tutorial2.Schematic_PM_Tutorial2_C
            ScannableResourceClassCleanlist:
              - /Game/FactoryGame/Resource/RawResources/Stone/Desc_Stone.Desc_Stone_C
      - path: mRecipeClassAllowlist
        value:
          # Mods
          - /AllMapRadar/
          - /MagicMachine/FluidSpawner/
          - /MagicMachine/Rec_Magic
          - /MagicMachine/MagicEnergy/
          - /MagicMachine/NewMagic/
          - /MagicMachine/UniversalSink/
          - /MagicMachine/Stackable/
          - /PeriodicMadness/
          # Generic matches
          - BladeRunners
          - Blueprint
          - Cartridge
          - CentralStorage
          - Chainsaw
          - ConveyorAttachment
          - ConveyorBelt
          - ConveyorCeilingAttachment
          - ConveyorLift
          - ConveyorPole
          - ConveyorWallHole
          - Customization/PaintFinishes
          - Customization/Patterns
          - Customization/Swatches
          - FactoryCart
          - Filter
          - FoundationPassthrough
          - Gasmask
          - GeneratorBiomass
          - GeneratorCoal
          - Hyper
          - IndustrialTank
          - Inhaler
          - JumpPad
          - LandingPad
          - LightsControlPanel
          - LookoutTower
          - Mam
          - Nobelisk
          - ObjectScanner
          - Packager
          - Parachute
          - Pipeline
          - PipeStorage
          - PipeSupport
          - PortableMiner
          - PortalPotty
          - PowerCrystalShard
          - PowerPole
          - PowerSwitch
          - PowerTower
          - Rebar
          - ResourceSink
          - Rifle
          - StackableShelf
          - StandaloneWidgetSign
          - StorageContainer
          - StorageHazard
          - StorageMedkit
          - StoragePlayer
          - StreetLight
          - Tractor
          - TradingPost
          - TruckStation
          - Valve
          - VehiclePath
          - WorkBench
          - Workshop
          - XenoBasher
          - XenoZapper
          - ZipLine
          # Specific recipes
          - Recipe_AlienDNACapsule
          - Recipe_Biomass_AlienProtein
          - Recipe_Material_Foundation_Default
          - Recipe_Miner
          - Recipe_OilPump
          - Recipe_Protein
          - Recipe_WaterPump
          # More specific recipes
          - Doors/Recipe_BigGarageDoor_16x8.
          - Doors/Recipe_Gate
          - FicsitSet/Recipe_Stair_FicsitSet
          - FicsitSet/Recipe_QuarterPipeMiddle
          - Foundations/Recipe_Foundation_8
          - Foundations/Recipe_QuarterPipe
          - Ramps/Recipe_RampInverted
          - Ramps/Recipe_Ramp_8x1_01
          - Ramps/Recipe_Ramp_8x2_01
          - Ramps/Recipe_Ramp_8x4_01
          - Ramps/Recipe_Ramp_8x4_Inverted_01
          - Ramps/Recipe_Ramp_8x8
          - Ramps/Recipe_Ramp_Diagonal
          - Ramps/Recipe_RampDouble
          - Recipe_PowerLine.Recipe_PowerLine
          - TowTruck/Recipe_SpaceElevator
          - Walls/Recipe_Wall_8x4_01
          - Walls/Recipe_Wall_Conveyor_8x4_01.
          - Walls/Recipe_Wall_Conveyor_8x4_02.
          - Walls/Recipe_Wall_Conveyor_8x4_03.
          - Walls/Recipe_Wall_Door_8x4_01.
          - Walls/Recipe_Wall_Door_8x4_03.
          - Walls/Recipe_Wall_Gate
          - Walls/Recipe_Wall_Orange
          - Walls/Recipe_Wall_Window
      - path: mItemClassAllowlist
        value:
          # Mods
          - /AllMapRadar/
          - /MagicMachine/
          - /PeriodicMadness/
          # Generic matches
          - AnimalParts
          - Blueprint
          - Cartridge
          - CentralStorage
          - Chainsaw
          - ConveyorAttachment
          - ConveyorBelt
          - ConveyorCeilingAttachment
          - ConveyorLift
          - ConveyorPole
          - ConveyorWallHole
          - Customization/PaintFinishes
          - Customization/Patterns
          - Customization/Swatches
          - Environment
          - FactoryCart
          - Filter
          - FoundationPassthrough
          - Gasmask
          - GeneratorBiomass
          - GeneratorCoal
          - GolfCart
          - Hyper
          - IndustrialTank
          - JumpingStilts
          - JumpPad
          - LandingPad
          - LightsControlPanel
          - LookoutTower
          - Mam
          - Medkit
          - Miner
          - Nobelisk
          - ObjectScanner
          - Packager
          - Parachute
          - Pipeline
          - PipeStorage
          - PortableMiner
          - PortalPotty
          - PowerPole
          - PowerSwitch
          - PowerTower
          - Rebar
          - ResourceSink
          - Rifle
          - ShockShank
          - StackableShelf
          - StandaloneWidgetSign
          - StorageContainer
          - StorageHazard
          - StorageMedkit
          - StoragePlayer
          - StreetLight
          - StunSpear
          - Tractor
          - TradingPost
          - TruckStation
          - Valve
          - VehiclePath
          - WorkBench
          - Workshop
          - ZipLine
          # Specific items
          - Desc_AlienDNACapsule
          - Desc_AlienProtein
          - Desc_Geyser
          - Desc_HardDrive
          - Desc_OilPump
          - Desc_WAT1
          - Desc_WAT2
          - Desc_WaterPump
          # More specific items
          - Desc_PowerLine.Desc_PowerLine
          - Doors/Desc_BigGarageDoor_16x8.
          - Doors/Desc_Gate
          - FicsitSet/Desc_Stair_FicsitSet
          - FicsitSet/Desc_QuarterPipeMiddle
          - FicsitWallSet/Desc_Wall_Orange_8x1
          - Foundation/Desc_Foundation_8
          - Foundation/Desc_QuarterPipe.Desc_QuarterPipe
          - Foundation/Desc_QuarterPipe_02
          - Foundation/Desc_QuarterPipeCorner
          - Ramp/Desc_RampInverted
          - Ramp/Desc_Ramp_8x1_01
          - Ramp/Desc_Ramp_8x2_01
          - Ramp/Desc_Ramp_8x4_01
          - Ramp/Desc_Ramp_8x4_Inverted_01
          - Ramp/Desc_Ramp_8x8
          - Ramp/Desc_Ramp_Diagonal
          - Ramp/Desc_RampDouble
          - SpaceElevator/Desc_SpaceElevator
          - Wall/Desc_Wall_8x4_01
          - Wall/Desc_Wall_Conveyor_8x4_01.
          - Wall/Desc_Wall_Conveyor_8x4_02.
          - Wall/Desc_Wall_Conveyor_8x4_03.
          - Wall/Desc_Wall_Door_8x4_01.
          - Wall/Desc_Wall_Door_8x4_03.
          - Wall/Desc_Wall_Gate
          - Wall/Desc_Wall_Orange
          - Wall/Desc_Wall_Window
      - path: mResourceScannerAllowlist
        value:
          # Mods
          - /PeriodicMadness/
          # Generic matches
          - Geyser
