---
$schema: https://raw.githubusercontent.com/Satisfactory-KMods/KDataForge-Linter/refs/heads/main/src/kdataforge_linter/schemas/cdo.schema.yml
type: cdo
patches:
  - target: /Script/PeriodicMadness.PMCleanerSettings
    properties:
      - path: mStaticMeshesCleanlist
        value:
          # Caterium
          - /Game/FactoryGame/Resource/RawResources/Nodes/ResourceNode_OreGold_01.ResourceNode_OreGold_01
          # Copper
          - /Game/FactoryGame/Resource/RawResources/Nodes/ResourceNode_OreCopper_01.ResourceNode_OreCopper_01
          # Iron
          - /Game/FactoryGame/Resource/RawResources/Nodes/ResourceNode_OreIron_01.ResourceNode_OreIron_01
          # Nitrogen
          - /Game/Developers/gabrielestigliano/NitrogenNode/SM_Nitrogen_Node_Mid.SM_Nitrogen_Node_Mid
          - /Game/Developers/gabrielestigliano/NitrogenNode/SM_Nitrogen_Node_Small.SM_Nitrogen_Node_Small
          - /Game/Developers/gabrielestigliano/NitrogenNode/SM_Nitrogen_Node_Crack.SM_Nitrogen_Node_Crack
          # Quartz
          - /Game/FactoryGame/Resource/RawResources/Nodes/ResourceNode_quartz.ResourceNode_quartz
          # Sulfur
          - /Game/FactoryGame/Resource/RawResources/Nodes/SulfurResource_01.SulfurResource_01
      - path: mResourceClassAllowlist
        value:
          # Mods
          - /PeriodicMadness/
          # Generic matches
          - Geyser
          - LiquidOil
          - SAM
          - Uranium
          - Water
          # must be allowed to be replaced
          - Coal
          - Stone
      - path: mResourceClassReplacements
        value:
          - Target: /Game/FactoryGame/Resource/RawResources/Coal/Desc_Coal.Desc_Coal_C
            Replacement: /PeriodicMadness/Resources/Products/RawResources/Coal/Desc_PM_Coal.Desc_PM_Coal_C
          - Target: /Game/FactoryGame/Resource/RawResources/Stone/Desc_Stone.Desc_Stone_C
            Replacement: /PeriodicMadness/Resources/Products/RawResources/Stone/Desc_PM_Stone.Desc_PM_Stone_C
      - path: mResearchTreeClassAllowlist
        value:
          # Mods
          - /PeriodicMadness/
          # Generic matches
          - HardDrive
      - path: mSchematicClassAllowlist
        value:
          # Mods
          - /AllMapRadar/
          - /FreeSigns/
          - /MagicMachine/
          - /PeriodicMadness/
          # Generic matches
          - Boombox
          - CoffeeCup
          - InventorySlots
          - Patterns
          - Pioneercosmetics
          - SaveCompatibility
          - Statue
          - Tapes
      - path: mRecipeClassAllowlist
        value:
          # Mods
          - /AllMapRadar/
          - /Fabricator/
          - /FreeSigns/
          - /MagicMachine/Rec_Magic
          - /MagicMachine/MagicEnergy/
          - /MagicMachine/NewMagic/
          - /MagicMachine/UniversalSink/
          - /MagicMachine/Stackable/
          - /PeriodicMadness/
          # Generic matches
          - Customization/PaintFinishes
          - Customization/Patterns
          - Customization/Swatches
          - StandaloneWidgetSign
          # Specific recipes
          - Recipe_Foundation_8x1_01
      - path: mItemClassAllowlist
        value:
          # Mods
          - /AllMapRadar/
          - /FreeSigns/
          - /MagicMachine/
          - /PeriodicMadness/
          # Generic matches
          - AnimalParts
          - Environment
          - ConveyorBelt
          - ConveyorCeilingAttachment
          - ConveyorLift
          - ConveyorPole
          - GeneratorBiomass
          - Mam
          - Pipeline
          - PortableMiner
          - ShockShank
          - StandaloneWidgetSign
          - TradingPost
          - WorkBench
          - Workshop
          # Specific items
          - Desc_Foundation_8x1_01
          - Desc_Geyser
          - Desc_HardDrive
          - Desc_Leaves
          - Desc_LiquidOil
          - Desc_Mycelia
          - Desc_Wood
          - Desc_WAT1
          - Desc_WAT2
          - Desc_Water
          # More specific items
          - SAM/Desc_SAM
          - SpaceElevator/Desc_SpaceElevator
