[AccessTransformers]

Friend=(Class="AFGDropPod", FriendClass="APMCleanerSubsystem")
Friend=(Class="UFGFoliageResourceUserData", FriendClass="APMCleanerSubsystem")
Friend=(Class="UFGRecipe", FriendClass="UPMCleanerWorldModule")
Friend=(Class="AFGRecipeManager", FriendClass="UPMCleanerWorldModule")
Friend=(Class="AFGResearchManager", FriendClass="UPMCleanerWorldModule")
Friend=(Class="UFGResearchTree", FriendClass="APMCleanerSubsystem")
Friend=(Class="AFGResourceScanner", FriendClass="APMCleanerSubsystem")
Friend=(Class="AFGResourceNodeBase", FriendClass="APMCleanerSubsystem")
Friend=(Class="AFGResourceNodeBase", FriendClass="UPMCleanerWorldModule")
Friend=(Class="UFGSchematic", FriendClass="APMCleanerSubsystem")
Friend=(Class="AFGSchematicManager", FriendClass="UPMCleanerWorldModule")
Friend=(Class="UFGUnlockRecipe", FriendClass="APMCleanerSubsystem")
Friend=(Class="UFGUnlockScannableResource", FriendClass="APMCleanerSubsystem")
Friend=(Class="AFGUnlockSubsystem", FriendClass="UPMCleanerWorldModule")
Friend=(Class="AFGWaterVolume", FriendClass="APMCleanerSubsystem")

; Custom FGIconLibrary
EditAnywhere=(Class="/Script/FactoryGame.IconData", Property="ID")
EditAnywhere=(Class="/Script/FactoryGame.IconData", Property="IconType")
EditAnywhere=(Class="/Script/FactoryGame.IconData", Property="ItemDescriptor")
EditAnywhere=(Class="/Script/FactoryGame.IconData", Property="DisplayNameOverride")
