[AccessTransformers]

Friend=(Class="UFGRecipe", FriendClass="UPMCleanerWorldModule")
Friend=(Class="AFGRecipeManager", FriendClass="UPMCleanerWorldModule")
Friend=(Class="AFGResearchManager", FriendClass="UPMCleanerWorldModule")
Friend=(Class="UFGResearchTree", FriendClass="UPMCleanerWorldModule")
Friend=(Class="AFGResourceScanner", FriendClass="APMCleanerSubsystem")
Friend=(Class="AFGResourceNodeBase", FriendClass="APMCleanerSubsystem")
Friend=(Class="AFGResourceNodeBase", FriendClass="UPMCleanerWorldModule")
Friend=(Class="UFGSchematic", FriendClass="UPMCleanerWorldModule")
Friend=(Class="AFGSchematicManager", FriendClass="UPMCleanerWorldModule")

; Custom FGIconLibrary
EditAnywhere=(Class="/Script/FactoryGame.IconData", Property="ID")
EditAnywhere=(Class="/Script/FactoryGame.IconData", Property="IconType")
EditAnywhere=(Class="/Script/FactoryGame.IconData", Property="ItemDescriptor")
EditAnywhere=(Class="/Script/FactoryGame.IconData", Property="DisplayNameOverride")
